baseURL = 'https://questions.jagunbae.com/'
languageCode = 'ko'
title = '질문 있는 사람들'
theme = 'blank'
HUGO_VERSION = "0.124.1"

[params]
  description = "마음속에 질문을 품고 주체적으로 살아가는 사람들. 그들의 일터로 직접 찾아가서 이야기 나누며 내가 가진 질문을 깊게 이해하는 투어 모임입니다."
  favicon = "images/favicon.png"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true